name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matootie/github-docker@v2.2.3
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          #repo-token: ${{ secrets.GITHUB_TOKEN }}
          #accessToken: ${{ secrets.packages }}
